### ISSUE TITLE
Using this module to read RX16 data

### ISSUE THREAD

**Issue by xseignard** [jankolkmeier/xbee-api#2]
Hello,
I'm trying to use your module to read RX16Responses from a XBee serie 1 in API mode  (AP=2). But I'm unable since the given frame type (0x81) seems to be missing in your lib. Am I right?

Did you had this working with xbee serie 1?

Regards,

Xavier

**Comment by KyleKing** [comment]
I'm having a similar issue with my code from the example for serialport:
```JS
var util = require('util');
var SerialPort = require('serialport').SerialPort;
var xbee_api = require('xbee-api');

var C = xbee_api.constants;

var xbeeAPI = new xbee_api.XBeeAPI({
  api_mode: 2
});

var serialport = new SerialPort("/dev/tty.usbserial-AH016D5G", {
  baudrate: 9600,
  parser: xbeeAPI.rawParser()
});

serialport.on("open", function() {
  var frame_obj = { // AT Request to be sent to
    type: C.FRAME_TYPE.AT_COMMAND,
    command: "NI",
    commandParameter: [],
  };

  serialport.write(xbeeAPI.buildFrame(frame_obj));
});

// All frames parsed by the XBee will be emitted here
xbeeAPI.on("frame_object", function(frame) {
    console.log(">>", frame.data);
});
```

The error is:
```shell
>> <Buffer 31 32 34 2c 33 38 2e 39 39 31 30 35 37 2c 2d 37 36 2e 39 33 38 31 31 33 2c 30 30 30>
>> <Buffer 31 32 34 2c 33 38 2e 39 39 31 30 35 37 2c 2d 37 36 2e 39 33 38 31 31 33 2c 30 30 30>
>> <Buffer 31 32 34 2c 33 38 2e 39 39 31 30 35 37 2c 2d 37 36 2e 39 33 38 31 31 33 2c 30 30 30>
>> <Buffer 31 32 34 2c 33 38 2e 39 39 31 30 35 37 2c 2d 37 36 2e 39 33 38 31 31 33 2c 30 30 30>

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Checksum Mismatch {"buffer":[126,0,40,144,0,94,0,6,136,1,78,73,0,32,191,126,0,40,144,0,19,162,0,64,197,248,186,142,255,1,49,50,52,44,51,56,46,57,57,49,48,53,55,44,0,0,0,0,40,134,0,4,1,0,0,0,14,34,0,0,1,0,0,0,120,139,0,4,1,0,0,0,128,140,0,4,1,0,0,0,184,127,0,4,1,0,0,0,1,0,0,0,0,0,0,0,112,131,0,4,1,0,0,0,248,138,0,4,1,0,0,0,0,0,0,0,1,0,0,0,240,151,102,0,1,0,0,0],"offset":44,"length":40,"total":3006,"checksum":44,"b":44,"escape_next":false,"waiting":true}
    at XBeeAPI.parseRaw (/Users/kyleking/Developer/Meteor/TeamBIKES/node_modules/xbee-api/lib/xbee-api.js:190:19)
    at XBeeAPI.<anonymous> (/Users/kyleking/Developer/Meteor/TeamBIKES/node_modules/xbee-api/lib/xbee-api.js:133:10)
    at Object.SerialPort.opts.dataCallback (/Users/kyleking/Developer/Meteor/TeamBIKES/node_modules/serialport/serialport.js:181:12)
    at SerialPortFactory.SerialPort._emitData (/Users/kyleking/Developer/Meteor/TeamBIKES/node_modules/serialport/serialport.js:396:20)
    at afterRead (/Users/kyleking/Developer/Meteor/TeamBIKES/node_modules/serialport/serialport.js:372:20)
    at /Users/kyleking/Developer/Meteor/TeamBIKES/node_modules/serialport/serialport.js:388:9
    at Object.wrapper [as oncomplete] (fs.js:454:17)
```

and this always occurs on the fifth frame?

**Comment by KyleKing** [comment]
Solved. I integrated the Xbee-API into my existing serialPort code (not sure why the example had issues though?):
```JS
// Name serial port - there should be a smarter way to do this, but this seems easiest
// Using terminal, identify with:
// ls /dev/cu.*
// ls /dev/cu.usbserial-* # for zigbee
// ls /dev/cu.usbmodem* # for arduino

var currentPort = "/dev/tty.usbserial-AH016D5G"; // Direct left Zigbee

var DDPClient = require("ddp");
var moment = require('moment');
moment().format();

var util = require('util');
var SerialPort = require('serialport').SerialPort;

var xbee_api = require('xbee-api');
var C = xbee_api.constants;
var xbeeAPI = new xbee_api.XBeeAPI({
  api_mode: 2
});

// Connect to Meteor
var ddpclient = new DDPClient({
  host: "localhost",
  port: 3000,
  /* optional: */
  auto_reconnect: true,
  auto_reconnect_timer: 500,
  use_ejson: true,  // default is false
  use_ssl: false, //connect to SSL server,
  use_ssl_strict: true, //Set to false if you have root ca trouble.
  maintain_collections: true //Set to false to maintain your own collections.
});

ddpclient.connect(function(error) {
  // Error Checking
  if (error) {
    console.log('DDP connection error!');
    return;
  }
  console.log('connected to Meteor!');

  // Configure serial port
  var serialPort = new SerialPort(currentPort, {
    // baudrate: 115200,
    baudrate: 9600,
    // baudrate: 57600,
    parser: xbeeAPI.rawParser()
  });

  // All frames parsed by the XBee will be emitted here
  xbeeAPI.on("frame_object", function(frame) {
    console.log(">>", frame);
  });

  // SerialPort events - trigger specific functions upon specific events
  serialPort.on('open', function() {
    console.log('port open. Data rate: ' + serialPort.options.baudRate);
  });
  serialPort.on('close', function() {
    console.log('port closed.');
  });
  serialPort.on('error', function(error) {
    console.log('Serial port error: ' + error);
  });
});
```
