### ISSUE TITLE
Checksum error when using AP Mode 2

### ISSUE THREAD

**Issue by mlamoure** [jankolkmeier/xbee-api#9]
Trying to get a basic debugging setup for my XBee's.  I notice once I turn the AP mode to 2, I get checksum errors.  I'm fairly certain the sender is creating correct frames because I can reproduce it with XCTU's frame generator.

BTW, thanks for taking up this project, I'm really excited about some things I'm going to do with it.

Stack trace:
/home/pi/node_modules/xbee-api/lib/xbee-api.js:173
        throw new Error("Checksum Mismatch", S);
              ^
Error: Checksum Mismatch
    at XBeeAPI.parseRaw (/home/pi/node_modules/xbee-api/lib/xbee-api.js:173:15)
    at Object.parser (/home/pi/node_modules/xbee-api/lib/xbee-api.js:119:10)
    at Object.SerialPort.options.dataCallback (/home/pi/node_modules/serialport/serialport.js:136:15)
    at SerialPortFactory.SerialPort._emitData (/home/pi/node_modules/serialport/serialport.js:305:20)
    at afterRead (/home/pi/node_modules/serialport/serialport.js:283:18)
    at /home/pi/node_modules/serialport/serialport.js:297:9
    at Object.wrapper [as oncomplete](fs.js:454:17)

**Comment by KyleKing** [comment]
I'm having the same issues. What was wrong with your setup?
